version: "3.9"  # docker-compose file version

services:
  canchem-api:
    image: ghcr.io/dongminl/canchem-api:1.2 # 불러올 Spring Boot 서버 이미지
    container_name: canchem-api # 컨테이너 이름
    depends_on:
      - canchem-redis # redis 먼저 생성
    ports:
      - "8080:8080" # 실행시킬 포트 (로컬 포트 : 도커 포트)
    networks:
      - canchem-network # Docker 내부 네트워크 지정

  canchem-redis:
    image: ghcr.io/dongminl/canchem-redis:1.2 # 불러올 Redis 이미지
    container_name: canchem-redis # 컨테이너 이름
    ports:
      - "6379:6379" # 포트 번호 지정
    command: redis-server /usr/local/etc/redis/redis.conf # 실행할 Command 명령어
    volumes:
      - ../redis.conf:/usr/local/etc/redis/redis.conf # Redis conf 파일 지정
    networks:
      - canchem-network # Docker 내부 네트워크 지정

networks:
  canchem-network:
    driver: bridge  # bridge로 네트워크 설정