spring:
  application:
    name: MolecularSearch

  jpa:
    open-in-view: false # OSIV 끄기 (성능과 확장성 향상)
    properties:
      hibernate:
        format_sql: true  # 쿼리문 가독성 높임
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql # MySQL 사용 명시
    hibernate:
      ddl-auto: create-drop  # 스키마 자동 생성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # \uD14C\uC774\uBE14 \uC774\uB984\uC744 \uC9C0\uC815\uD55C \uADF8\uB300\uB85C \uC0AC\uC6A9
    show-sql: true  # SQL 문으로 log 표시

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 연동
    url: jdbc:mysql://127.0.0.1:3306/canchem?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # DB URL 연결
    username: root  # MySQL 아이디
    password: Dongmin5677@  # MySQL 비밀번호

server:
  servlet:
    session:
      tracking-modes: cookie  # 세션 쿠기

# JPA 로깅 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE  # 파라미터 보여주기
        SQL: debug  # 디버깅 레벨로 쿼리 출력